#!/bin/sh
# usage: cruft_wall /path/to/image
# you can use fbv or idump
set -eu

if [ "${1:-}" = "" ]; then
	echo "usage: $0 /path/to/image" >&2
	exit 1
fi

# fbv (http://www.eclis.ch/fbv/)
printf '\033[?25l' # hide cursor
fbv -ciuker "$1" <<EOF
q
EOF

# idump (https://github.com/uobikiemukot/idump)
#idump "$1"

export CRUFT="wall"
exec cruft
